repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: fix-encoding-pragma
- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
    - id: black
- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.9.0  # Use the ref you want to point at
  hooks:
    - id: python-use-type-annotations
    - id: python-no-log-warn
    - id: python-no-eval
- repo: https://github.com/asottile/reorder_python_imports
  rev: v3.1.0
  hooks:
    - id: reorder-python-imports
- repo: local
  hooks:
    - id: pylint
      name: pylint
      entry: pylint
      language: system
      types: [python]
      args:
        [
          "-rn", # Only display messages
          "-sn", # Don't display the score
          "--rcfile=.pylintrc", # Link to your config file
          "--load-plugins=pylint.extensions.docparams", # Load an extension
        ]
